version: '3.2'
services:
  db:
    restart: always
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=asd123
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./backend:/home/app
      - ./production/static/img:/home/app/app/static/img
  
  server:
    restart: always
    build: ./server
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./production/static:/static
      - ./production:/usr/share/nginx/html