version: '3.2'
services:
  db:
    restart: always
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=asd123
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./backend:/home/app
  
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - /home/app/node_modules
      - ./frontend:/home/app